### ISSUE TITLE
Create Shower CRD

### ISSUE THREAD

**Issue by tumido** [AICoE/meteor-operator#15]
Add a new CR that:
- Deploys `Shower` UI
- Is singleton per namespace
- All `Meteors` within that namespace belongs to it
- Will holds default and global configs.

```yaml
apiVersion: meteor.operate-first.cloud/v1alpha1
kind: Shower
metadata:
  name: default
spec:
```

Future work:
1. Make Shower deploy and manage Shower UI, no CR config required, this will be turned on by default
2. Extend with global config for external services that are sourced by each meteor - like which namespace is JH located at
3. Extend with default configs like workspace specification
4. Extend default configs with optional specifications like push-to-quay secrets etc.
