### ISSUE TITLE
Enable pipeline discovery through operator

### ISSUE THREAD

**Issue by tumido** [AICoE/meteor-operator#52]
Operator should discover all available meteor pipelines and sync them to the `Shower` resource status.

Operator should discover all tekton`Pipeline`s resources with given annotations and sync in into a new status property of Shower resource

It expects following annotaions on `Pipeline` resource:

```yaml
kind: Pipeline
metadata:
  annotations:
    meteor.zone/pipeline: "true"
    shower.meteor.zone/default-state: "true"  # optional annotation, assume enabled if not set
spec:
    description: "foo bar baz"
```

```yaml
kind: Shower
status:
  pipelines:
    - name: <name>
      defaultState: "true"
      description: "foo bar baz"
```

1. Create new status field in `ShowerStatus` implemented as an Array of `PipelineSpec` with mandatory fields `name` (string) and `enabled` (bool) 
2. Add a function which discovers all `Pipeline` resources matching given annotation selector
3. Populate the status field
