### ISSUE TITLE
Allow selective on/off of individual pipelines in Shower config

### ISSUE THREAD

**Issue by tumido** [AICoE/meteor-operator#53]
Follow up after https://github.com/AICoE/meteor-operator/issues/52

Enhance the `Shower` spec from previous issue with:

```yaml
kind: Shower
spec:
  pipelines:
    - name: <name>
      defaultState: "true"  # Has precedence over Pipeline resource annotation 
      enabled: "true"  # If true, this pipeline can't be submitted even if selected in the Meteor spec 
status:
  pipelines:
    - name: <name>
      defaultState: "true" 
      enabled: "false"
```
