### ISSUE TITLE
Configure button labels in the pipeline resource instead of hardcoding it

### ISSUE THREAD

**Issue by tumido** [AICoE/meteor-operator#56]
Follow up after https://github.com/AICoE/meteor-operator/issues/52
Similar to: https://github.com/AICoE/meteor-operator/issues/53
Backed support for: https://github.com/AICoE/meteor/issues/113

Expect following labels on `Pipeline` resource:

```yaml
kind: Pipeline
metadata:
  annotations:
    shower.meteor.zone/button: Read docs with JupyterBook
```

Enhance the `Shower` spec from previous issue:

```yaml
kind: Shower
status:
  pipelines:
    - name: <name>
      button: Read docs with JupyterBook
```
